### PR TITLE
Antlr and Java upgrade for Spring boot 3.x

### PR DESCRIPTION
**Pull request by monishagarwal215**

### CODE REVIEW

**Comment by oscarmorasu** [comment]
@bohnman , I see interest in the community to maintain this. The main reason would be keeping up with the dependencies.
Would you be open to open this to contributors?

**Comment by monish-cashify** [comment]
@bohnman I would like to upgrade this for Java 21. For now we have fix locally at our end.

**Comment by bohnman** [comment]
Unfortunately, I don't have cycles to maintain this anymore. However, I would entertain a transfer of ownership if someone is interested in taking it over.

**Comment by monish-cashify** [comment]
@bohnman I would love to take this responsibility, if you interested we can get in touch.

**Pull request closed without merging**
